# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/java_backend
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/JuCanEat

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

keycloak.auth-server-url=http://localhost:8081
keycloak.realm=JuCanEat

#Ours
aiservice.mock-implementation-active=false