# JPA/Hibernate - datasource injected via K8s Secret env vars
spring.jpa.hibernate.ddl-auto=validate

# Flyway disabled - CI pipeline runs migrations before deployment
spring.flyway.enabled=false

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/JuCanEat

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
