# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres_java_backend:5432/java_backend
spring.datasource.username=java_backend
spring.datasource.password=java_backend
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

microservice.url=http://python-microservice:8000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/JuCanEat
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/JuCanEat/protocol/openid-connect/certs

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

keycloak.auth-server-url=http://localhost:8081
keycloak.realm=JuCanEat

spring.ai.openai.api-key=placeholder

#Ours
aiservice.mock-implementation-active=false