services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./multiple-db:/docker-entrypoint-initdb.d
    networks:
      - jucaneat-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL_DATABASE=keycloak
      - KC_HOSTNAME=localhost
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
    command: start-dev --import-realm
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./imports:/opt/keycloak/data/import
      - ./providers:/opt/keycloak/providers
    networks:
      - jucaneat-net

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_USER=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jucaneat-net

volumes:
  postgres-data:
  elasticsearch-data:

networks:
  jucaneat-net:
    driver: bridge