apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    {{- include "java-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ required "postgres.url is required" .Values.postgres.url | quote }}
  username: {{ required "postgres.username is required" .Values.postgres.username | quote }}
  password: {{ required "postgres.password is required" .Values.postgres.password | quote }}
