package com.backend.controllers;

import com.backend.model.dtos.DailyMenuDTO;
import com.backend.model.dtos.RestaurantDetailsDTO;
import com.backend.model.dtos.RestaurantListDTO;
import com.backend.services.MenuService;
import com.backend.services.RestaurantService;
import com.backend.services.SseEmitterService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.List;
import java.util.Map;
import java.util.UUID;
@RestController
@RequestMapping("/api/menus")
@RequiredArgsConstructor
@Tag(name = "Menus", description = "Endpoints for retrieving restaurants daily menu")
@CrossOrigin(origins = "http://localhost:3000")
public class MenuController {
    private final MenuService menuService;
    private final SseEmitterService sseEmitterService;
    @Operation(
            summary = "Get restaurant daily menu draft by restaurant ID",
            description = "Retrieves draft generated by ocr of daily menu for given restaurant"
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successfully retrieved daily menu draft"),
            @ApiResponse(responseCode = "404", description = "Restaurant not found")
    })
    @GetMapping("/{id}/draft")
    @PreAuthorize("hasRole('restaurant_owner')")
    public ResponseEntity<DailyMenuDTO> getDailyMenuDraftByRestaurantId(
            @Parameter(description = "Id of the restaurant", required = true)
            @PathVariable UUID id) {

        DailyMenuDTO dailyMenu = menuService.getDailyMenuDraftByRestaurantId(id);
        return ResponseEntity.ok(dailyMenu);
    }

    @Operation(
            summary = "Get restaurant daily menu by restaurant ID",
            description = "Retrieves daily menu for given restaurant"
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successfully retrieved restaurant details"),
            @ApiResponse(responseCode = "404", description = "Restaurant not found")
    })
    @GetMapping("/{id}")
    public ResponseEntity<DailyMenuDTO> getDailyMenuByRestaurantId(
            @Parameter(description = "Id of the restaurant", required = true)
            @PathVariable UUID id) {

        DailyMenuDTO dailyMenu = menuService.getDailyMenuByRestaurantId(id);
        return ResponseEntity.ok(dailyMenu);
    }

    @Operation(
            summary = "Process daily menu image for restaurant by ID",
            description = "Processes new daily menu for the restaurant with given id."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successfully retrieved restaurant details"),
            @ApiResponse(responseCode = "404", description = "Restaurant not found"),
            @ApiResponse(responseCode = "403", description = "User is not the owner of the restaurant"),
    })

    @PostMapping
    @PreAuthorize("hasRole('restaurant_owner')")
    public ResponseEntity<Void> ProcessDailyMenuImage(
            @RequestParam("restaurantId") UUID restaurantId,
            @RequestParam("image") MultipartFile image,
            @AuthenticationPrincipal Jwt jwt,
            @RequestHeader Map<String, String> headers ) {
        String ownerId = jwt.getSubject();

        menuService.uploadMenuImage(restaurantId, image, ownerId);
        return ResponseEntity.accepted().build();
    }

    @Operation(
            summary = "Add new daily menu by menuId",
            description = "Adds new active daily menu"
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Successfully retrieved restaurant details"),
            @ApiResponse(responseCode = "404", description = "Restaurant not found")
    })
    @PutMapping("/{id}")
    @PreAuthorize("hasRole('restaurant_owner')")
    public ResponseEntity<Void> updateMenu(@PathVariable UUID id,
                                           @RequestBody DailyMenuDTO request,
                                           @AuthenticationPrincipal Jwt jwt) {
        String ownerId = jwt.getSubject();
        menuService.updateAndApproveMenu(id, request, ownerId);
        return ResponseEntity.ok().build();
    }

    @GetMapping("/events")
    public SseEmitter subscribe(@AuthenticationPrincipal Jwt jwt) {
        String ownerId = jwt.getSubject();
        return sseEmitterService.createEmitter(ownerId);
    }
}
